/**
 * Export utilities for audit reports.
 */

export function exportJSON(data: unknown, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });
  downloadBlob(blob, filename);
}

/**
 * Export a simple text-based PDF-like report.
 * Uses the browser print API for proper PDF generation.
 */
export function exportPDF(title: string, sections: { heading: string; content: string }[]) {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${escapeHtml(title)}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #1c1917; }
        h1 { font-size: 24px; border-bottom: 2px solid #d97706; padding-bottom: 8px; margin-bottom: 24px; }
        h2 { font-size: 16px; color: #57534e; text-transform: uppercase; letter-spacing: 1px; margin-top: 24px; }
        p { line-height: 1.6; font-size: 14px; }
        .meta { color: #78716c; font-size: 12px; margin-bottom: 24px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
        .badge-pass { background: #d1fae5; color: #065f46; }
        .badge-fail { background: #fee2e2; color: #991b1b; }
        .verdict { padding: 12px; margin: 8px 0; background: #fafaf9; border-radius: 8px; border-left: 3px solid #d97706; }
        .certified { margin-top: 24px; padding: 16px; background: #ecfdf5; border-radius: 12px; text-align: center; }
        .certified strong { color: #065f46; font-size: 18px; }
        @media print { body { padding: 0; } }
      </style>
    </head>
    <body>
      <h1>CLAW:FE SPOT — Audit Report</h1>
      <div class="meta">
        <strong>${escapeHtml(title)}</strong><br />
        Generated: ${new Date().toLocaleString()}<br />
        Report ID: ${crypto.randomUUID?.() ?? Math.random().toString(36).slice(2)}
      </div>
      ${sections
        .map(
          (s) => `
        <h2>${escapeHtml(s.heading)}</h2>
        <div>${s.content}</div>
      `,
        )
        .join("")}
      <hr style="margin-top: 40px; border: none; border-top: 1px solid #e7e5e4;" />
      <div class="meta" style="margin-top: 16px;">
        This report was generated by CLAW:FE SPOT audit system.<br />
        Integrity verification should be performed using the JSON export hash chain.
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeHtml(str: string) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
